### ISSUE TITLE
react-seed: Consume v6 alphas and build Penta demo

### ISSUE THREAD

**Issue by nicolethoen** [patternfly/patternfly-react-seed#168]
Once the following components have been built out using new design tokens, the core + react v6 alphas can be pulled into the react-seed to build out a Penta demo:

```[tasklist]
### Core Tasks
- [x] #175
- [x] EmptyState (https://github.com/patternfly/patternfly/issues/5733)
- [x] SkipToContent (https://github.com/patternfly/patternfly/issues/6088)
- [x] Title (https://github.com/patternfly/patternfly/issues/5730)
- [x] Brand (https://github.com/patternfly/patternfly/pull/6132)
- [x] Button (https://github.com/patternfly/patternfly/issues/5998)
- [x] Masthead (https://github.com/patternfly/patternfly-react/pull/9853)
- [x] Nav (https://github.com/patternfly/patternfly/issues/6000)
- [x] Page (https://github.com/patternfly/patternfly-react/issues/9808)
- [x] Text (https://github.com/patternfly/patternfly/issues/5730)
```

```[tasklist]
### React Tasks
- [ ] https://github.com/patternfly/patternfly-react/issues/9928
- [ ] https://github.com/patternfly/patternfly-react/issues/9857
- [ ] https://github.com/patternfly/patternfly-react/issues/9681
- [ ] https://github.com/patternfly/patternfly-react/issues/9921
- [ ] https://github.com/patternfly/patternfly-react/issues/9907
- [ ] https://github.com/patternfly/patternfly-react/issues/9809
- [ ] https://github.com/patternfly/patternfly-react/issues/9943
- [ ] https://github.com/patternfly/patternfly-react/issues/9808
```

```[tasklist]
### Penta review
- [ ] Design review
- [ ] Core review
- [ ] React review
```

```[tasklist]
### Demo enhancements (new branch off of V6)
- [ ] https://github.com/patternfly/patternfly-react-seed/issues/205
```

**Comment by kmcfaul** [comment]
Should be updated with latest alphas and re-verified.

**Comment by nicolethoen** [comment]
- @patternfly/patternfly: 6.0.0-alpha.117
- @patternfly/react-charts@8.0.0-alpha.19
- @patternfly/react-code-editor@6.0.0-alpha.50
- @patternfly/react-core@6.0.0-alpha.50
- @patternfly/react-docs@7.0.0-alpha.52
- @patternfly/react-drag-drop@6.0.0-alpha.31
- @patternfly/react-icons@6.0.0-alpha.19
- @patternfly/react-styles@6.0.0-alpha.19
- @patternfly/react-table@6.0.0-alpha.50
- @patternfly/react-tokens@6.0.0-alpha.19

**Comment by nicolethoen** [comment]
We should update both the following PRs:
- https://github.com/patternfly/patternfly-react-seed/pull/209 (plus https://pf6-seed-demo.surge.sh/)
- https://github.com/patternfly/patternfly-react-seed/pull/192
