### ISSUE TITLE
React Seed demo screens for Penta

### ISSUE THREAD

**Issue by andrew-ronaldson** [patternfly/patternfly-react-seed#200]
To provide a more interesting demonstration of Penta, create a demo app based on the React seed. 
Desirable features include:

- Light/dark theme switcher
- RTL switcher
- Navigation between a couple of pages showing content, such as a gallery of cards or table.

Design work
- [x] patternfly/patternfly-design#1281

Core work
Nothing needed?

```[tasklist]
### React work
- [ ] https://github.com/patternfly/patternfly-react-seed/issues/202
- [ ] https://github.com/patternfly/patternfly-react-seed/issues/203
- [ ] https://github.com/patternfly/patternfly-react-seed/issues/204
```

**Comment by andrew-ronaldson** [comment]
### Overview page
**Design:** [Overview page](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/74knFIPjVGdvLZ0eEDraJp/Penta-Component-Library?type=design&node-id=15135-44263&mode=design&t=N1kMvcQkzSRjMia2-0)
**Page example:** [Primary details card view](https://www.patternfly.org/patterns/dashboard#basic) 

### Resources page
**Design:** [Resources page](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/74knFIPjVGdvLZ0eEDraJp/Penta-Component-Library?type=design&node-id=15135%3A44810&mode=design&t=zLLDuTXhkmc8qyHe-1)
**Page example:** [Primary details card view](https://www.patternfly.org/patterns/primary-detail#primary-detail-card-view) 

### Filters page
**Design:** [Inventory page](https://www.figma.com/file/VMEX8Xg2nzhBX8rfBx53jp/branch/74knFIPjVGdvLZ0eEDraJp/Penta-Component-Library?type=design&node-id=15135%3A48150&mode=design&t=zLLDuTXhkmc8qyHe-1)
**Page example:** [Attribute filter page](https://www.patternfly.org/patterns/filters#attribute-search)
